### ISSUE TITLE
Dynamically updating source causes duplicate destination

### ISSUE THREAD

**Issue by barmmie** [czeckd/angular-dual-listbox#16]
Hi,

Thanks for your work on this. I have an issue i would like some help with at your convenience.

I have tried to implement a ajax search to the listbox that allows the user to search and update the source with the results.
However whenever i make a new ajax search this causes the destination to duplicate and i can't seem to figure out why.

Any pointers would be helpful.
Thanks

**Comment by czeckd** [comment]
A little more detail would be helpful since without the code, I can only guess. 

Where are you doing the search? Outside the ``DualListComponent`` or did you modify the component to add search? Does the source array input to the ``DualListComponent`` get modified by the search?

Are you seeing the duplication in the destination array, or in the ``confirmed.list`` in the ``DualListComponent`` itself?

**Comment by czeckd** [comment]
I took a first pass at adding a filter to the ``DualListComponent``. The code is in the project's [filter](https://github.com/czeckd/angular2-dual-listbox/tree/filter) branch.

**Comment by barmmie** [comment]
Hi,

I would create a plunkr to demonstrate my implementation and the resulting issue. (Currently on mobile).
Would also check out the filter branch for any pointers 

I am doing the search in the DualListComponent. I am working on a slightly modified version.
I am emitting the search term on key stroke as an @Output and leaving the implementation of the ajax search to the parent component.
In the parent component I then set the source array on success callback of the ajax.
yes, the source array is getting modified by the search.

The duplication is in the confirmed.list.

**Comment by czeckd** [comment]
Okay, please share a plunkr with an example. I'll take a look when you get it posted.

**Comment by czeckd** [comment]
Also since you're changing the source, have you thought about filtering your source array outside of the ``DualListComponent``? I think that approach would lead to less code and allow for the component's change detection work more effectively.

**Comment by barmmie** [comment]
Hi,
@czeckd 
Here is my implementation, It allows me to set the source from remote
[http://plnkr.co/edit/C5ysvDYc67IRYtoAdh7p?p=preview](http://plnkr.co/edit/C5ysvDYc67IRYtoAdh7p?p=preview)

Sorry regards the delay, I had trouble creating the plunkr (My first time).

I have been able to resolve the issue. It was caused by me not your plugin.

If you would like to add an optional remote search into this component, i could make a PR over the weekend.

Thanks very much for your time.

**Comment by czeckd** [comment]
Congratulations on getting your search working!

I would recommend refactoring your implementation to move the query to build the users array outside the ``DualListComponent``, because the way it is currently implemented is: 1. get query string in ``DualListComponent``; 2. emit query string to parent; 3. parent makes query to datasource; 4. parent updates users array; 5. ``DualListComponent`` available array is updated.

So, the code flow takes a little longer path to update ultimately the ``DualListComponent`` available list array. What I suggest is move the search into the parent component. This refactoring would encapsulate concerns cleanly: 1. parent updates query; 2. parent makes query to data source; 3. parent updates users array; 4. `DualListComponent`` available array is updated. The circular round-trip is eliminated.

Here is a plunkr with my suggested refactoring: http://plnkr.co/edit/sxz1dYJ7uIK48WPepF1S?p=preview

These are the few minor changes to the parent ``App``:
```typescript
export class App implements OnInit {
  users:any[] = [];
  selected_users:any[] = [];
  
  querySource: Subject<string> = new Subject<string>();
  queryAvailable: string = '';

  constructor(private http:Http) {
  }
  
  ngOnInit() {
    this.querySource.debounceTime(500).distinctUntilChanged()
      .subscribe(query => {
        this.getListOfUsers(query);
      });
  }
  
  getListOfUsers(query) {
    this.http.get('https://api.github.com/search/users?q='+ query)
      .map(res => res.json())
      .subscribe((res) => {
        this.users = res.items;
      });
  }

  queryAvailableChanged(text: string) {
    this.querySource.next(text);
  }
}
```

And adding to the template:
```html
  <div class="row">
    <form>
      <div class="col-sm-5 input-group">
        <span class="input-group-addon" id="basic-addon1"><i class="fa fa-search"></i></span>
          <input type="text" name="queryAvailable" 
          (ngModelChange)="queryAvailableChanged($event)" 
          class="form-control" placeholder="Search..." 
          aria-describedby="basic-addon1" [(ngModel)]="queryAvailable">
      </div>
    </form>
  </div>
```

This would provide a clean separation between the ``DualListComponent`` and the query-populated source. Good luck!

**Comment by barmmie** [comment]
Hi,

I agree with you, and had gone that route initially.
I eventually settled for this approach for code reuse, since
DualListComponent is being used in a lot of components currently (5) in my
project, and didn't want to reimplement search in all those components, or
in future components


Thanks again for the work on this plugin.

**Comment by czeckd** [comment]
Fair enough. I'm glad you're finding the component useful. 
Please star the project if you think of it. It helps others find it.
Good luck!
