### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by danilomcb** [czeckd/angular-dual-listbox#42]
Hello! I'm using the component in a project, but I'm having performance issues.

In an editing scenario, I have to initialize the destination list with the chosen elements in the register. I am having problems initializing, when the target list has more than 1500 elements. Pretty much my system stops working.

Any idea what might be causing this?

**Comment by czeckd** [comment]
Yes, I did not predict that this component would be used with arrays that big! 

The problem is that `trueUp` is, politely put, inefficient. It iterates over every item in the confirmed list and then does a array filter on the destination and potentially the source. The way `moveItem` is written, each time an item is added to the destination, `trueUp` is called. Thus, this is the performance issue you're seeing.

There is a minor code change that I can make to `moveItem` that will get at least 10k items in the destination. It isn't instant, but it will work. I'll publish the modification tomorrow if it passes the tests.

**Comment by czeckd** [comment]
Try version 4.3.1 and see if that works better for your use case of more than 1500 elements in the destination list.

**Comment by danilomcb** [comment]
I just completed the tests. It has improved considerably. There is a small delay, but it is within the expected! 

Thank you very much!

**Comment by czeckd** [comment]
You're welcome. I'll look into further performance enhancements in upcoming releases too.
