### ISSUE TITLE
Problem sharing the same source

### ISSUE THREAD

**Issue by crisarjim** [czeckd/angular-dual-listbox#73]
Hi, actually I think this is not an issue per se, but it seems to be like GitHub records everything as "Issues", sorry in advance.

Here is my situation; I've been testing this component and it is reaaaally cool, now, I have just a minor problem. I want to share the same Source between list-boxes, let me try to be more specific.

Let's say the Source is a list of shoes(the difference is the color, then I have blue, red, green, black and white shoes in this list), and the Destination  are clients whom can buy those shoes(ClientA, ClientB and ClientC); currently, when I try to set the 3 different clients to share the same source, I notice that after adding the blue shoes for ClientA, when I swap to ClientB or ClientC the Source still the same, it still have  blue, red, green, black and white shoes for choosing, when actually, the blue ones should be not available.

Is this scenario already taken into account?, thank you, I'll be waiting for you reply.

**Comment by czeckd** [comment]
The dual-listbox does not change the source array.

If you need to change the source in response to something being added to the destination, then hook a function to the `destinationChange` event to add/remove selected options in the source array as needed.

```html
<dual-list [source]="source" [(destination)]="confirmed"
    (destinationChange)="myModify($event)">
</dual-list>
```

```typescript
myModify(dest:Array<any>) {
     // Do stuff to source based on the current destination array.
}
```

**Comment by crisarjim** [comment]
Hi @czeckd , I've tried using your suggestion, but it still not working for me.
Since I need to have the same source(a list of shoes; red, blue, black, etc) shared between destinations(I plan to have N clients for buying the shoes), I'm using the "destinationChange" for updating the source; my function looks like:
`
    myModify(dest:Array<any>) {
        let forDeletion = dest;
        this.source = this.source.filter(item => !forDeletion.includes(item))
...
...
`
The problem here is  after doing  the filter; it updates the source removing the moved item(s)(and that's great), but the destination loses the item as well!.
Any other suggestion?. I really would appreciate it!..

**Comment by czeckd** [comment]
Keep a copy of the original array and subtract from it what is in the destination as returned by the destinationChange event.
```typescript
import { Component } from '@angular/core';

@Component({
    selector: 'app-root',
    template: `
        <div class="container">
            <dual-list [source]="source" [(destination)]="target" height="150px"
                (destinationChange)="modify($event)"></dual-list>
        </div>
        <div style="display:flex">
            <pre>{{source|json}}</pre>
            <pre>{{target|json}}</pre>
        </div>`,
    styles: [ '.container { margin-top: 12px; }' ]
})
export class AppComponent {
    source = [ 'Pawn', 'Rook', 'Knight', 'Bishop', 'Queen', 'King' ];
    target = [];
    private original = this.source.slice(0);

    modify(arr) {
        this.source = this.original.filter( e => arr.indexOf(e) < 0); 
    }
}
```

**Comment by crisarjim** [comment]
Thank you very much for your time!!, checking now, keep you posted with the result.

**Comment by crisarjim** [comment]
Hi @czeckd, I already chech your suggestion, and it is working... partially; I mean, now I have no problems with source!, that's great, but confirmed instead.

![sample](https://user-images.githubusercontent.com/36654661/36638173-160bb662-19b3-11e8-9618-0333494af3d1.png)

In the attached image, as you can see, I have 3 Clients(A,B,C); for each of them, I selected a pair of shoes, in the *console.log*:
 * ClientA: Black Shoes
 * ClientB: White Shoes
 * ClientC: Red Shoes

The problem I hace now is, as soon as I get back to ClientA or ClientB, the UI is not rendering the list for confirmed values!; I've tried using ChangesDetect and NgZones, but it seems to be like the dual-list component is stronger.

Have you seen something similar?.

**Comment by czeckd** [comment]
The `dual-list` really was not designed to work with your use case. So, you're stretching it in ways that break the component's primary design assumption.

The primary `dual-list` assumption is that the source provides a universal list of items for the destination. If the item is not in the source at the time it is added to the destination, then it will not be added to the destination since there is no source. 

Think of `dual-list` as a multi-select list where the options are the source and the selected options are the destination.

My guess is that each time you go to a different client, the `dual-list` is reconstructed, preserving no state from the prior time it was used. (I don't know for certain, since you've not posted your test program's code.) The upshot is since your code eliminate picks from the source once they are in the destination and then navigate away from one client to another, the source is missing the items when it navigates to the other client's `dual-list`. 

You might possibly work around this by having 3 dual-lists all with the same source, but using the `[hidden]="false"` attribute on a parent `<div>` to select only the one you want to see. (Using `*ngif` will not solve it since it removes and recreates the `dual-list` in the DOM.) This approach may work, but I haven't tested the theory. 

Another option is to maintain 3 sources, one for each client. Each client's source would have any not selected items plus their own selected items. That seems like a lot of effort to me, though. There are probably other options, but it will involve writing hacks around `dual-list` to make it stretch in a way that it was not designed to stretch.

So, you may be better off with writing your own component to manage the arrays in a way that follows your use case.

**Comment by crisarjim** [comment]
You are right, I've been trying hard to stretch your component since, aside the current problem I have, it is the best component out there for fulfill my task.
Any way, thank you for your time and patience, I'll give it a last chance, applying the suggestion you just posted; but probably I'll end up writing my own component(that's what I was avoiding since yours fits almost perfectly).
Thank you sir.
