### ISSUE TITLE
Binding Confirmed to Model

### ISSUE THREAD

**Issue by jkergosi** [czeckd/angular-dual-listbox#74]
This may be an easy one, but we'll see.

I'd like to had the dual listbox on a form and bind the confirmed values to the form's angular model. 
Ex:
<dual-list [key]="key" [display]="display" [(destination)]="model.categories" name="categories" #categories="ngModel" [(ngModel)]="model.categories" height="265px"></dual-list>

Is that feasible? If not, any recommendations on how to bind the confirm list to a model?

Thanks!
Jason

**Comment by czeckd** [comment]
Sorry, it'd require a rewrite to incorporate NgModel. The dual-list does, however, update the destination and can be used on template-driven forms. You will need to provide a source for the component though.

**Comment by jkergosi** [comment]
Thank you for your quick response! I was thinking in lieu of this, is is maybe possible to do something like this (referencing your code in a different issue):

<dual-list [source]="source" [(destination)]="confirmed"
    (destinationChange)="myModify($event)">
</dual-list>

myModify(dest:Array<any>) {
     model.categories = dest;
}

I think this might be a decent workaround. Thoughts?

**Comment by czeckd** [comment]
In the example you posted, the `[(destination)]="model.categories"` will update with changes caused by using the `dual-list`. So, as items are selected from the source and then added to the destination, the destination array `model.categories` will update with those changes. The component does not use NgModel, but the model.categories array will update accordingly.

So maybe I do not understand what you are trying to have happen. Please post a code example if you are trying to accomplish something different.
